stages:
  - commit
  - acceptance
  - deploy

.assume_role: &assume_role
  - >
    STS=($(aws sts assume-role-with-web-identity
    --role-arn ${AWS_ROLE_ARN}
    --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
    --web-identity-token $ID_TOKEN
    --duration-seconds 3600
    --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
    --output text))
  - export AWS_ACCESS_KEY_ID="${STS[0]}"
  - export AWS_SECRET_ACCESS_KEY="${STS[1]}"
  - export AWS_SESSION_TOKEN="${STS[2]}"

CLIENT_BUILD:
  image: node:20-alpine
  stage: commit
  script:
    - cd rose-client
    - npm install
    - npm run build
  artifacts:
    paths:
      - rose-client/dist

CLIENT_DEPLOY_STAGING:
  image:
    name: amazon/aws-cli:latest
    entrypoint:
      - '/usr/bin/env'
  id_tokens:
    ID_TOKEN:
      aud: rose_directory_client_s3
  stage: acceptance
  script:
    - *assume_role
    - aws s3 sync rose-client/dist s3://${S3_BUCKET}/staging/client
    - aws cloudfront create-invalidation --distribution-id ${STAGING_DISTRIBUTION_ID} --paths "/index.html"

CLIENT_DEPLOY_PRODUCTION:
  image:
    name: amazon/aws-cli:latest
    entrypoint:
      - '/usr/bin/env'
  id_tokens:
    ID_TOKEN:
      aud: rose_directory_client_s3
  stage: deploy
  when: manual
  script:
    - *assume_role
    - aws s3 sync rose-client/dist s3://${S3_BUCKET}/production/client
